name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore .NET dependencies (Chạy trong thư mục backend nếu cần)
      - name: Restore .NET dependencies
        run: |
          cd backend  # Chuyển đến thư mục chứa solution file
          dotnet restore WoodWorkshop.sln

      # Build .NET project
      - name: Build .NET project
        run: |
          cd backend  # Chạy lệnh build trong thư mục backend
          dotnet build WoodWorkshop.sln --configuration Release

      # Các bước deploy cho frontend hoặc các bước tiếp theo của bạn.
