name: Build and Deploy

on:
  push:
    branches: ["production"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Cài NodeJS để build React
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cài đặt & build frontend React
      - name: Install dependencies & build React
        run: |
          cd frontend
          npm install
          npm run build

      # Upload build folder làm artifact để deploy lên GitHub Pages
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

      # Cài .NET SDK để kiểm tra backend
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build .NET (nếu chỉ để kiểm tra backend không lỗi)
      - name: Restore & Build .NET
        run: |
          dotnet restore backend/WoodWorkshop/WoodWorkshop.sln
          dotnet build backend/WoodWorkshop/WoodWorkshop.sln --configuration Release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
