name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copy React build to wwwroot
        run: |
          mkdir -p backend/WoodWorkshop/wwwroot
          rm -rf backend/WoodWorkshop/wwwroot/*
          cp -r frontend/build/* backend/WoodWorkshop/wwwroot/

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore backend/WoodWorkshop.sln

      - name: Build .NET project
        run: dotnet build backend/WoodWorkshop.sln --configuration Release
